MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnext_backbone
    NORM: BN
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    WITH_SE: True  
    PRETRAIN: False

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    EMBEDDING_DIM: 512
    WITH_BNNECK: True
    POOL_LAYER: GlobalAvgPool  #AdaptiveAvgMaxPool GlobalAvgPool GlobalMaxPool FastGlobalAvgPool ClipGlobalAvgPool GeneralizedMeanPoolingP GeneralizedMeanPooling
    NECK_FEAT: before  
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss","TripletLoss","Cosface",)

    CE:
      EPSILON: 0.1
      ALPHA: 0.2
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 0.5

    COSFACE:
      MARGIN: 0.35
      GAMMA: 64
      SCALE: 1.0

    ARCFACE:
      MARGIN: 0.35
      SCALE: 30.0
    
    COMBINED_MARGIN_LOSS:
      M1: 1.0
      M2: 0.75
      M3: 0.0
      SCALE: 64.0

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  REA:
    ENABLED: True
    PROB: 0.3 

  FLIP:
    ENABLED: True
    PROB: 0.5 

  PADDING:
    ENABLED: False

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler   ####
  NUM_INSTANCE: 4 ###
  NUM_WORKERS: 8 ###

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True