weights: pretrained/yolov7-w6.pt
cfg: yolov7/cfg/training/yolov7-w6-AICUP.yaml
data: D:\3B012059\AIcup_2024\AICUP_Baseline_BoT-SORT-main\yolov7\data\AICUP.yaml
hyp: D:\3B012059\AIcup_2024\AICUP_Baseline_BoT-SORT-main\yolov7\data\hyp.scratch.p5.yaml
epochs: 100
batch_size: 8
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolo_data_random_aux_Conv_epoch_100
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\yolo_data_random_aux_Conv_epoch_100
total_batch_size: 8
